"use strict";
//Conditional Tests: Write a series of conditional tests. Print a statement describing each test and your prediction for the results of each test. Your code should look something like this:
let car = "Audi";
console.log("car == 'Audi is good car' i predict true ");
console.log(car == "Audi");
let weapon = "M416";
console.log("weapon == 'M416 best assault rifle' i predict true");
console.log(weapon == "M416");
let explore = "Dubai";
console.log("explore == 'turkey good country for enjoy' i predict true");
console.log(explore == "turkey");
let adventure = "skydive";
console.log("adventure == 'skydive i love fly' i predict true");
console.log(adventure == "skydive");
let atm = "money";
console.log("atm == 'money can buy happiness' i predict true");
console.log(atm == "money");
let passenger = 200;
console.log("is passenger == in bus '150' i predict that allow ");
console.log(passenger == "150");
let frnd = "musawir";
console.log("frnd == 'yousuf my best one' i predict false");
console.log(frnd == "yousuf");
let dress = "shalwarkameez";
console.log("dress == 'paintshirt good looking dress' i predict false");
console.log(dress == "painshirt");
let bike = "Ninja H2r";
console.log("bike == 'yahmahaR1 is fastest heavy bike' i predict false");
console.log(bike == "yahmahaR1");
let fastFood = "burger";
console.log("fastFood == 'pizza good fastfood of alimran resturant' i predict false");
console.log(fastFood == "burger");
